- name: Install helms
  hosts: localhost
  tasks:
    - name: Instal helm
      become: true
      ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add cert-manager chart repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Add kube-prometheus-stack chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Add grafana chart repo
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: "https://grafana.github.io/helm-charts"

    - name: Add traefik chart repo
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"

    - name: Add csi-driver-nfs chart repo
      kubernetes.core.helm_repository:
        name: csi-driver-nfs
        repo_url: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"

    - name: Instal core applications
      ignore_errors: true
      block:
        - name: Deploy csi-driver-nfs
          kubernetes.core.helm:
            name: csi-driver-nfs
            chart_ref: csi-driver-nfs/csi-driver-nfs
            release_namespace: kube-system
            values: "{{ lookup('file', './values/csi-driver-nfs.yaml') | from_yaml }}"
            chart_version: "v4.2.0"
        - name: Deploy kube-prometheus-stack
          kubernetes.core.helm:
            name: kube-prometheus-stack
            chart_ref: prometheus-community/kube-prometheus-stack
            release_namespace: monitoring
            values: "{{ lookup('file', './values/kube-prometheus-stack.yaml') | from_yaml }}"
            chart_version: "45.8.1"
        - name: Deploy loki
          kubernetes.core.helm:
            name: loki
            chart_ref: grafana/loki
            release_namespace: monitoring
            values: "{{ lookup('file', './values/loki.yaml') | from_yaml }}"
            chart_version: "5.0.0"
        - name: Deploy cert-manager
          kubernetes.core.helm:
            name: cert-manager
            chart_ref: jetstack/cert-manager
            release_namespace: cert-manager
            values: "{{ lookup('file', './values/cert-manager.yaml') | from_yaml }}"
            chart_version: "v1.11.0"
        - name: Deploy traefik
          kubernetes.core.helm:
            name: traefik
            chart_ref: traefik/traefik
            release_namespace: traefik
            values: "{{ lookup('file', './values/traefik.yaml') | from_yaml }}"
            chart_version: "v22.0.0"
      module_defaults:
        kubernetes.core.helm:
          create_namespace: true
          kubeconfig: /home/vagrant/.kube/config

    - name: Apply manifests
      ignore_errors: true
      block:
        - name: Storage class
          kubernetes.core.k8s:
            src: ./files/manifests/storageclass.yaml
        - name: CA Secret
          kubernetes.core.k8s:
            src: ./files/manifests/cacert-secret.yaml
        - name: Cluster issuer
          kubernetes.core.k8s:
            src: ./files/manifests/cluster-issuer.yaml
        - name: Traefik dashboard
          kubernetes.core.k8s:
            src: ./files/manifests/traefik-dashboard-ingress.yaml
      module_defaults:
        kubernetes.core.k8s:
          state: present
