- name: Install helms
  hosts: helm
  tasks:
    - name: Instal helm
      become: true
      ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add cert-manager chart repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Add kube-prometheus-stack chart repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Instal core applications
      ignore_errors: true
      block:
        - name: Deploy kube-prometheus-stack
          kubernetes.core.helm:
            name: kube-prometheus-stack
            chart_ref: prometheus-community/kube-prometheus-stack
            release_namespace: monitoring
            values: "{{ lookup('file', './values/kube-prometheus-stack.yaml') | from_yaml }}"
        - name: Deploy cert-manager
          kubernetes.core.helm:
            name: cert-manager
            chart_ref: jetstack/cert-manager
            release_namespace: cert-manager
            values: "{{ lookup('file', './values/cert-manager.yaml') | from_yaml }}"
      module_defaults:
        kubernetes.core.helm:
          create_namespace: true
          kubeconfig: /home/vagrant/kubeconfig

    - name: Apply manifests
      ignore_errors: true
      block:
        - name: CA Secret
          kubernetes.core.k8s:
            src: ./files/manifests/cacert-secret.yaml
        - name: Cluster issuer
          kubernetes.core.k8s:
            src: ./files/manifests/cluster-issuer.yaml
      module_defaults:
        state: present
